# Stage 1: Build
FROM node:20-slim AS builder

WORKDIR /app
RUN npm install -g pnpm

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY packages/common/package.json ./packages/common/
COPY backend/package.json ./backend/

RUN pnpm install --filter @prnews/backend...

COPY . .

ENV NODE_ENV=production
RUN pnpm --filter @prnews/backend... run build

RUN pnpm --filter @prnews/backend deploy --prod --legacy /deploy


# Stage 2: Production
FROM node:20-slim

WORKDIR /app

ENV NODE_ENV=production
ENV HOST=0.0.0.0

COPY --from=builder /deploy .
COPY backend/entrypoint.sh .

# Fix line endings and make the entrypoint script executable
RUN sed -i 's/\r$//' entrypoint.sh
RUN chmod +x entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]

